title: Carlos Herrera Valerio
logo: /assets/img/profile_photo_1-1_rounded.jpg
description: Electronic Engineer | 9+ years of experience | Data Science | Analog testing
email: carlos.herrera.valerio@gmail.com
show_download: true
theme: jekyll-theme-minimal
